[meta]
is_python_project = true
uses_ansible = false
meta_version = "0.5.dev0"
project_name = "brostar"
package_name = "brostar"
extra_package_names = ["api", "gmn", "gmw", "gld", "frd", "gar"]
minimum_coverage = "10"
