version: '2'

services:

  db:
    image: postgis/postgis:14-3.4
    environment:
      POSTGRES_USER: 'brostar'
      POSTGRES_PASSWORD: 'brostar'
      POSTGRES_DB: 'brostar'
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:latest
    expose:
      - 6379

  celery:
    environment:
      # # Can be set in .env, we'll pass them on. settings.py has some defaults.
      - FIELD_ENCRYPTION_KEY
      - SECRET_KEY
      - NENS_AUTH_ISSUER
      - NENS_AUTH_CLIENT_ID
      - NENS_AUTH_CLIENT_SECRET
    build: .
    command: celery -A brostar_api worker --loglevel=INFO
    volumes:
      - .:/code
    links:
      - redis
    depends_on:
      - db
      - redis

  web:
    environment:
      # # Can be set in .env, we'll pass them on. settings.py has some defaults.
      - FIELD_ENCRYPTION_KEY
      - SECRET_KEY
      - NENS_AUTH_ISSUER
      - NENS_AUTH_CLIENT_ID
      - NENS_AUTH_CLIENT_SECRET
    build: .
    # command: "bin/gunicorn -b 0.0.0.0:${PORT:-5000} --workers=3 --timeout 90 --preload --max-requests=10000 trs.wsgi"
    command: "python manage.py runserver 0.0.0.0:8000"
    links:
      - db
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
      - celery


volumes:
  pgdata:
