version: '2'

services:

  db:
    image: mdillon/postgis
    environment:
      POSTGRES_USER: 'bro_hub'
      POSTGRES_PASSWORD: 'bro_hub'
      POSTGRES_DB: 'bro_hub'
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  web:
    build: .
    # command: "bin/gunicorn -b 0.0.0.0:${PORT:-5000} --workers=3 --timeout 90 --preload --max-requests=10000 trs.wsgi"
    command: "python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    restart: unless-stopped
    environment:
      # # Can be set in .env, we'll pass them on.
      # - SECRET_KEY
      - DEBUG
      - FIELD_ENCRYPTION_KEY
      # - SENTRY_DSN
      # - NENS_AUTH_ISSUER
      # - NENS_AUTH_CLIENT_ID
      # - NENS_AUTH_CLIENT_SECRET

volumes:
  pgdata:
